name: Docker Compose Workflow

on:
  push:
    branches:
      - master  # Change this from 'main' to 'master'

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and start Docker containers
      run: |
        sudo docker-compose -f ./src/main/resources/ReportIo/docker-compose.yml up -d

    - name: Check container status
      run: |
        sudo docker-compose -f ./src/main/resources/ReportIo/docker-compose.yml ps
